name: tawafuq_alajhiza
description: توافقات الأجهزة - منصة توافق قطع غيار الهواتف والأجهزة
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/catalog.json
    - assets/data/sources.json
